# Generated by Django 2.0.7 on 2018-07-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя продукта')),
                ('article', models.CharField(max_length=20, unique=True, verbose_name='артикул товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='products_images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('kolichestvo', models.PositiveIntegerField(default=0, verbose_name='кол-во товара')),
            ],
            options={
                'ordering': ['-price', 'kolichestvo', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=64, unique=True, verbose_name='имя бренда')),
                ('description', models.TextField(blank=True, verbose_name='описание брэнда')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_catalog', models.CharField(max_length=64, unique=True, verbose_name='имя каталога')),
                ('description', models.TextField(blank=True, verbose_name='описание каталога')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя категории')),
                ('discount', models.FloatField(blank=True, default=0, verbose_name='скидка на категорию')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=64, unique=True, verbose_name='цвет товара')),
                ('description', models.TextField(blank=True, verbose_name='описание цвета')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_size', models.CharField(max_length=64, unique=True, verbose_name='цвет товара')),
                ('description', models.TextField(blank=True, verbose_name='описание размера')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='Catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ProductCatalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ProductColor'),
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.ProductSize'),
        ),
    ]
